---
- hosts: ios
  name: "Cleanup BGP configuration from Cisco IOS"
  tags: clean
  tasks:
  - ios_command: 
      commands: "show ip protocols summary | include bgp"
    register: protocols
  - set_fact: bgp_as="{% set r = protocols.stdout[0] %}{{ r | regex_replace('^.*bgp\s+(\d+)$','\\1') }}"
  - ios_config:
      lines:
        - "no router bgp {{bgp_as}}"
    when: "{{ bgp_as }}"

- hosts: ios
  name: "Create BGP process on Cisco IOS"
  tags: create
  tasks:
  - ios_config:
      lines:
        - "router bgp 123"
