---
- hosts: ios
  tasks:
  - ios_facts:
    register: facts
  - debug: var=facts

- hosts: nxos
  tasks:
  - nxos_facts:
    register: facts
  - debug: var=facts

- hosts: junos
  tasks:
  - junos_facts:
    register: facts
  - debug: var=facts

- hosts: eos
  tasks:
  - eos_facts:
    register: facts
  - debug: var=facts

