---
ansible_device_os: nxos

cli:
  username:  "{{ansible_user}}"
  password:  "{{ansible_password}}"
  host:      "{{inventory_hostname}}"
  transport: cli

nxapi:
  username:  "{{ansible_user}}"
  password:  "{{ansible_password}}"
  host:      "{{inventory_hostname}}"
  transport: nxapi